import React from "react";
import { Link } from "wouter";
import { copyTextSafely, shareTrackingLink } from "@/lib/tracking-actions";
import { toSafeAbsoluteStatusUrl } from "@/lib/latest-order";

export function CustomerTrackingActions({ reference, statusUrl, showViewButton = false, compact = false }: { reference: string; statusUrl?: string; showViewButton?: boolean; compact?: boolean }) {
  const [message, setMessage] = React.useState("");
  const [fallback, setFallback] = React.useState<"reference" | "link" | null>(null);
  const [busy, setBusy] = React.useState<"reference" | "share" | null>(null);
  const safeUrl = typeof window === "undefined" ? null : toSafeAbsoluteStatusUrl(statusUrl, window.location.origin);
  const copyReference = async () => { setBusy("reference"); setFallback(null); const copied = await copyTextSafely(reference); setBusy(null); if (copied) setMessage("Order reference copied."); else { setFallback("reference"); setMessage("Press and hold the reference to copy it."); } };
  const share = async () => { if (!safeUrl) return; setBusy("share"); setFallback(null); const result = await shareTrackingLink(reference, safeUrl, window.location.origin); setBusy(null); if (result === "shared") setMessage("Tracking link ready to share."); else if (result === "copied") setMessage("Tracking link copied. You can paste it into a text message or email."); else if (result === "manual") { setFallback("link"); setMessage("Could not copy the link. Press and hold the link below to copy it."); } };
  return <section className={compact ? "mt-4" : "mt-6 rounded-2xl border border-primary/15 bg-background/50 p-4"} aria-label="Order tracking actions"><div className="flex flex-wrap gap-3">{showViewButton && safeUrl && <a href={safeUrl} className="inline-flex min-h-12 items-center justify-center rounded-xl bg-primary px-5 text-base font-bold text-white focus-visible:outline focus-visible:outline-4 focus-visible:outline-secondary">View Order Status</a>}{safeUrl && <button type="button" onClick={share} disabled={busy !== null} className="min-h-12 rounded-xl border border-primary px-5 text-base font-bold text-primary focus-visible:outline focus-visible:outline-4 focus-visible:outline-secondary disabled:cursor-not-allowed disabled:opacity-60">{busy === "share" ? "Preparing…" : "Share Tracking Link"}</button>}<button type="button" onClick={copyReference} disabled={busy !== null} className="min-h-12 rounded-xl border border-primary/60 px-5 text-base font-bold text-primary focus-visible:outline focus-visible:outline-4 focus-visible:outline-secondary disabled:cursor-not-allowed disabled:opacity-60">{busy === "reference" ? "Copying…" : "Copy Order Reference"}</button>{!compact && <Link href="/track-order" className="inline-flex min-h-12 items-center justify-center px-3 font-bold text-primary underline">Back to Track Order</Link>}</div>{safeUrl && <p className="mt-3 text-sm text-foreground/70">This private link lets someone view your order status. Only share it with people you trust.</p>}<p aria-live="polite" className="mt-2 min-h-5 text-sm text-foreground/75">{message}</p>{fallback === "reference" && <input aria-label="Order reference to copy" value={reference} readOnly className="mt-2 min-h-12 w-full rounded-xl border border-primary/30 bg-white px-3 text-base" />}{fallback === "link" && safeUrl && <><input aria-label="Tracking link to copy" value={safeUrl} readOnly className="mt-2 min-h-12 w-full rounded-xl border border-primary/30 bg-white px-3 text-sm" /><p className="mt-2 text-sm text-foreground/70">Press and hold the link, then choose Copy.</p></>}</section>;
}
